update workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -9,8 +9,14 @@ jobs:
   build-and-push:
     runs-on: ubuntu-latest
     steps:
-      - name: Debug Docker Username
-        run: echo "Docker Username: ${{ secrets.DOCKERHUB_USERNAME }}"
+      - name: Check if Docker Username is available
+        run: |
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "Error: Docker Username not set!"
+            exit 1
+          else
+            echo "Docker Username is set."
+          fi
 
       - name: Check Out Repo
         uses: actions/checkout@v2
